/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:14e3a1ac-6036-415e-9e9c-9ca116af45a9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3R6pwXLQK",
    "aws_user_pools_web_client_id": "ug7v3h28cu0aqh643q634o2q5",
    "oauth": {}
};


export default awsmobile;
