/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:893f934c-0d2e-4fbb-ba0b-1cf216eb8bdf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9nQF1cbsi",
    "aws_user_pools_web_client_id": "38sjb1va6hodfr0iiu0e6bvar2",
    "oauth": {}
};


export default awsmobile;
